spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: sai@9079
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: "change-this-to-a-long-random-secret-key"
    expiration-ms: 86400000

